#!/usr/bin/env bash
# this script send a file to the server

if [[ $# -lt  3 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	if [[ -z $4 ]]; then 
		scp -o StrictHostKeyChecking=n0 "$1" "$2:~/"
	else
		scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
	fi
fi

