#!/usr/bin/env bash
# this script send a file to the server

if [[ $# -lt  3 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	if [[ -z $4 ]]; then 
		scp "$1" "$2:~/"
	else
		scp "$1" "$3@$2:~/" -i "$4"
	fi
fi

