#!/usr/bin/env bash
# this script installs nginx and setup index page

sudo apt update
sudo apt -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html;
}" > /etc/nginx/sites-available/default
service nginx start
