#!/usr/bin/env bash
# this script installs nginx and setup index page

sudo apt update
sudo apt -y install nginx
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html/;
    index  index.html;
    location /redirect_me {
        return 301 https://google.com/;
    }
}" > /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
service nginx start
