#!/usr/bin/env bash
# this script installs nginx and setup index page

new_string="
	server_name _
	
	location /redirect_me {
        	return 301 https://twitter.com/Emmanue17280546;
	}
"

sudo apt update
sudo apt -y install nginx
sed -i "s/server_name.*/$new_string/" /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
service nginx start
