#!/usr/bin/env bash
#print "TEXT" 10 times
# shellcheck disable=SC2034
TEXT="Best School"
i=0

while [ $i -lt 10 ];
do
	if [ $i -ne 8 ];
	then
		echo "$TEXT"
	else		
		echo "HI"
	fi
	i=$((i + 1))
done
