#!/usr/bin/env bash
#print "TEXT" 10 times
# shellcheck disable=SC2034
TEXT="Best School"
TEXT_BAD_JAPAN="bad luck from Japan"
TEXT_BAD_CHINA="bad luck from China"
TEXT_BAD_ITALY="bad luck from Italy"
i=1
MAX=20

while (( i <= MAX ));
do
	echo "$i"

	case "$i" in
		4)	echo "$TEXT_BAD_CHINA";;
		9)	echo "$TEXT_BAD_JAPAN";;
		17)	echo "$TEXT_BAD_ITALY";;
	esac
	i=$((i + 1))
done
