#!/usr/bin/env bash
#print "TEXT" 10 times
# shellcheck disable=SC2034
TEXT="Best School"
TEXT_BAD_JAPAN="bad luck from JAPAN"
TEXT_BAD_CHINA="bad luck from CHINA"
TEXT_BAD_ITALY="bad luck from ITALY"
i=1
MAX=20

while (( i <= MAX ));
do
	echo "$i"

	if (( i == 4 ));
	then
		echo "$TEXT_BAD_CHINA"
	elif (( i == 9 ))
	then
		echo "$TEXT_BAD_JAPAN"
	elif (( i == 17 ))
	then
		echo "$TEXT_BAD_ITALY"
	fi
	i=$((i + 1))
done
